### ISSUE TITLE
radarr on windows?

### ISSUE THREAD

**Issue by Zeusy123** [Dec64/pingrr#12]
Hi m8ty, thought today would try allowing your script to connect to radarr. put in correct info in config, but its throwing this error:

Traceback (most recent call last):
  File "pingrr.py", line 424, in <module>
    radarr_library = radarr.get_library()
  File "D:\Appz\pingrr\pingrr\radarr.py", line 50, in get_library
    r = requests.get(url + '/api/movie', headers=headers, timeout=60)
  File "C:\Python27\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Python27\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 612, in send
    adapter = self.get_adapter(url=request.url)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 703, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
requests.exceptions.InvalidSchema: No connection adapters were found for 'localhost:7878/api/movie'

**Comment by Zeusy123** [comment]
Anyone can help??

**Comment by Zeusy123** [comment]
dec64 where r youuuuuuuuuuuuuuuuuuuu ?:)

**Comment by Dec64** [comment]
Please do not spam, this isn't a commercial project, just a personal script i uploaded. I'm not going to give up all my free time for "customer support"

I'm not sure what that issue is, I assume sonarr connects.
